### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by tf2jaguar** [hantmac/juejinxiaoceToMobi#1]
这个是为什么啊？  请帮助我一下

widows10 + go最新稳定版

D:\Documents_Go\juejinxiaoceToMobi-master>go run main.go
main.go:3:8: cannot find package "github.com/hantmac/juejinxiaoceToMobi/processData" in any of:
        F:\Go\src\github.com\hantmac\juejinxiaoceToMobi\processData (from $GOROOT)
        D:\Documents_Go\src\github.com\hantmac\juejinxiaoceToMobi\processData (from $GOPATH)

D:\Documents_Go\juejinxiaoceToMobi-master>

**Comment by tf2jaguar** [comment]
我改变了main.go的路径，。又出现了一个问题。

D:\Documents_Go>go run src\juejinxiaoceToMobi\main.go
# juejinxiaoceToMobi/processData
src\juejinxiaoceToMobi\processData\process.go:1:15: syntax error: unexpected ., expecting semicolon or newline

**Comment by hantmac** [comment]
Sorry 回复晚了。
现在这个问题解决了吗？

**Comment by hantmac** [comment]
> 我改变了main.go的路径，。又出现了一个问题。
> 
> D:\Documents_Go>go run src\juejinxiaoceToMobi\main.go
> 
> # juejinxiaoceToMobi/processData
> src\juejinxiaoceToMobi\processData\process.go:1:15: syntax error: unexpected ., expecting semicolon or newline

缺失的包使用`go get `下载一下应该就可以

**Comment by hantmac** [comment]
我修改了下包路径，麻烦帮忙测试一下，感谢

**Comment by Geek-James** [comment]
必须买了才能抓吗?没有购买的可以抓不

**Comment by hantmac** [comment]
> 必须买了才能抓吗?没有购买的可以抓不

当然是必须买了才能抓啊，需要购买后的uuid, 不然掘金还不把我抓我来。┑(￣Д ￣)┍

**Comment by Geek-James** [comment]
视频可以抓到嘛..

**Comment by hantmac** [comment]
> 视频可以抓到嘛..

现在掘金小册出视频了？
这个版本还不支持

**Comment by hantmac** [comment]
> 视频可以抓到嘛..

Flutter是视频，可以下载，但是我木有购买

**Comment by tf2jaguar** [comment]
> 我修改了下包路径，麻烦帮忙测试一下，感谢

我将本地路径改为相对路径就可以了。删除了hantmac/juejinxiaoceToMobi前缀

**Comment by tf2jaguar** [comment]
请问有抓好的
 `深入理解 RPC : 基于 Python 自建分布式高并发 RPC 服务` 这本书吗

**Comment by hantmac** [comment]
> 请问有抓好的
> `深入理解 RPC : 基于 Python 自建分布式高并发 RPC 服务` 这本书吗

我没买这本书
