### ISSUE TITLE
mobi图片无法显示

### ISSUE THREAD

**Issue by xinyu-io** [hantmac/juejinxiaoceToMobi#4]
生成的mobi图片是无法显示的，都是md代码。
建议使用，pandoc：
https://pandoc.org/epub.html

生成epub。

**Comment by hantmac** [comment]
> 生成的mobi图片是无法显示的，都是md代码。
> 建议使用，pandoc：
> https://pandoc.org/epub.html
> 
> 生成epub。

mobi 确实无法显示图片。我研究下 pandoc 哈。
